name: 'Fetch All Secrets from Azure Key Vault'
description: 'Fetch all secrets from Azure Key Vault and pass them as environment variables in the workflow.'
inputs:
  azure_tenant_id:
    description: 'Azure Tenant ID'
    required: true
  azure_client_id:
    description: 'Azure Client ID'
    required: true
  azure_client_secret:
    description: 'Azure Client Secret'
    required: true
  key_vault_name:
    description: 'Azure Key Vault Name (e.g., https://<keyvault-name>.vault.azure.net/)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python dependencies
      shell: bash 
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install azure-identity azure-keyvault-secrets python-dotenv

    - name: Fetch Secrets from Azure Key Vault
      shell: bash
      run: |
        python3 vaulted.py
      env:
        AZURE_TENANT_ID: ${{ inputs.azure_tenant_id }}
        AZURE_CLIENT_ID: ${{ inputs.azure_client_id }}
        AZURE_CLIENT_SECRET: ${{ inputs.azure_client_secret }}
        KEY_VAULT_URL: ${{ inputs.key_vault_name }}
