name: CI/CD pipeline for image scanning

on:
  workflow_dispatch:

jobs:
  scan_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb

      - name: scan the image
        uses: docker://docker.io/aquasec/trivy:0.19.2
        with:
          args: image --exit-code 0 --severity HIGH,CRITICAL --no-progress myapp:latest

      - name: Upload Docker image as an artifact
        if: success()  # Only upload if the scan passes
        uses: actions/upload-artifact@v3
        with:
          name: myapp-docker-image
          path: myapp:latest

  image_push:
    needs: scan_image  # Depends on scan_image job
    runs-on: ubuntu-latest
    if: success()  # Runs only if scan_image job is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image from artifacts
        uses: actions/download-artifact@v3
        with:
          name: myapp-docker-image
          path: ./  # Downloads the image to the current directory

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
