name: CI/CD pipeline for image scanning
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image to scan'
        required: true
        default: 'myapp:latest'
        type: string

jobs:
  # Reusable workflow for scanning
  scan_image:
    uses: ./.github/workflows/scan.yml  # Call the reusable scan.yml workflow
    with:
      docker_image: ${{ inputs.docker_image }}

  # Job for pushing image after scan
  image_push:
    needs: scan_image  # This job depends on scan_image
    runs-on: ubuntu-latest
    if: success()  # Only run this job if scan_image is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image tarball from artifacts
        uses: actions/download-artifact@v3
        with:
          name: myapp-docker-image  # Artifact name should match the one uploaded in scan.yml
          path: ./  # Path to download the tarball to

      - name: Load Docker image from tarball
        run: |
          docker load -i ./myapp-image.tar  # Load the Docker image from the tarball

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag ${{ inputs.docker_image }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image }}
