name: CI/CI pipeline for image scanning
on:
   workflow_dispatch:

jobs:
  scan_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t myapp:latest .

      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb

      - name: scan the image
        uses: docker://docker.io/aquasec/trivy:0.19.2
        with:
          args: image --exit-code 0 --severity HIGH,CRITICAL --no-progress myapp:latest

  image_push:
    needs: scan_image
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}


      - name: docker tag and push
        run: |
            docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          
