name: CI/CI pipeline for image scanning
on:
   workflow_dispatch:

jobs:
  image_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v1
        with:
        # Relevant options for the `analyze` action
         output: codeql-results.sarif  # The SARIF output file location
         upload: true  # This will automatically upload the results to GitHub

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v1
        with:
         sarif_file: codeql-results.sarif         

      - name: build image
        run: docker build -t myapp:latest .

      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb

      - name: scan the image
        uses: docker://docker.io/aquasec/trivy:0.19.2
        with:
          args: image --exit-code 0 --severity HIGH,CRITICAL --no-progress myapp:latest
          
