name: Image Scan workflow
on:
  workflow_call:
    inputs:
      docker_image:
        description: 'Docker image to scan'
        required: true
        default: 'myapp'
        type: string
      docker_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
        type: string
jobs:
  scan_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t ${{ inputs.docker_image }}:${{ inputs.docker_tag }} .

      - name: Install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          rm trivy.deb

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.5.0
        with:
          image: ${{ inputs.docker_image }}:${{ inputs.docker_tag }}
          severity: HIGH,CRITICAL # Fail the build if vulnerabilities of these severities are found
          format: table
          exit-code: 0  # Fail the build if vulnerabilities are found

      - name: Upload Trivy report as an artifact
        uses: actions/upload-artifact@v3
        with:
            name: trivy-report
            path: trivy-report.json

      - name: Export Docker image to tarball
        run: |
          docker save ${{ inputs.docker_image }}:${{ inputs.docker_tag }} -o ${{ inputs.docker_image }}-${{ inputs.docker_tag }}.tar

      - name: Upload Docker image tarball as an artifact
        if: success()  # Only upload if the scan passes
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.docker_image }}-${{ inputs.docker_tag }}-image
          path: ${{ inputs.docker_image }}-${{ inputs.docker_tag }}.tar

