name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Run Unit Tests
      #   run: |
      #     # Example: Running Python tests
      #     python -m unittest discover -s tests

  security_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.34.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.34.0_Linux-64bit.deb
          rm trivy_0.34.0_Linux-64bit.deb

      - name: Scan Docker Image for Vulnerabilities
        run: |
          trivy image --exit-code 0 --no-progress --format table ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  push_image:
    runs-on: ubuntu-latest
    needs: [build, test, security_scan]
    steps:
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  
